#!/usr/bin/env python3
"""Generate build module reference documentation from build.py module definitions."""
import sys
from pathlib import Path

# Add parent directory to path to import build module
sys.path.insert(0, str(Path(__file__).parent.parent))
import build

def generate_reference() -> str:
    """Generate markdown reference for all build modules."""
    lines = [
        "# Build Module Reference",
        "",
        "This document is auto-generated by `tools/generate_build_reference.py`.",
        "Do not edit manually.",
        "",
        "## Modules",
        "",
        "| Module | Language | Directory | Build Command | Clean Command | Artifact Directory |",
        "|--------|----------|-----------|---------------|---------------|-------------------|",
    ]
    
    for module in build.MODULES:
        rel_dir = module.dir.relative_to(build.ROOT)
        build_cmd = ' '.join(module.build_cmd)
        clean_cmd = ' '.join(module.clean_cmd)
        artifact = str(module.build_dir.relative_to(build.ROOT)) if module.build_dir else "N/A"
        lines.append(f"| {module.name} | {module.language} | {rel_dir} | `{build_cmd}` | `{clean_cmd}` | {artifact} |")
    
    lines.extend([
        "",
        "## Usage",
        "",
        "### Build all modules",
        "",
        "```bash",
        "python3 build.py",
        "```",
        "",
        "### Build specific module(s)",
        "",
        "```bash",
        "python3 build.py --module backend",
        "python3 build.py --module backend,frontend",
        "```",
        "",
        "### Clean build artifacts",
        "",
        "```bash",
        "python3 build.py --clean",
        "python3 build.py --clean --module backend",
        "```",
        "",
        "### Release build (Rust only)",
        "",
        "```bash",
        "python3 build.py --release",
        "```",
        "",
        "### List available modules",
        "",
        "```bash",
        "python3 build.py --list",
        "python3 build.py --list-modules",
        "```",
    ])
    
    return '\n'.join(lines) + '\n'


def main():
    """Generate and write build module reference."""
    output_path = Path(__file__).parent.parent / "docs" / "BUILD_MODULES.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    content = generate_reference()
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
